using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Diagnostics;
using Newtonsoft.Json;
using CommandLine;
using System.Threading;

namespace CreatePluginFromTemplate.Automation
{
    class Package
    {
        public int FileVersion = 3;
        public int Version = 1;
        public string VersionName = "1.0";
        public string FriendlyName;
        public string Description = "Character package autogenerated for WellVr";
        public string Category = "Characters";
        public string CreatedBy = "AutoGenerated";
        public string CreatedByUrl = "";
        public string DocsUrl = "";
        public string MarketplaceUrl = "";
        public string SupportUrl = "";
        public bool CanContainContent = true;
        public bool IsBetaVersion = false;
        public bool Installed = false;
    }

    class Options
    {
        [Option('p', "projectdirectory", Required = true, HelpText = "Base directory for uproject.")]
        public string ProjectDirectory { get; set; }

        [Option('r', "uprojectname", Required = true, HelpText = "Name of Unreal project.")]
        public string UprojectName { get; set; }

        [Option('u', "unrealdirectory", Required = true, HelpText = "Unreal Root Directory.  Should end with something like 4_19/")]
        public string UnrealDirectory { get; set; }

        [Option('n', "pluginname", Required = false, HelpText = "Plugin name.  Generated if not available.")]
        public string PluginName { get; set; }

        public string GetUprojectPath()
        {
            return ProjectDirectory + "\\" + UprojectName;
        }
    }

    class Program
    {

        private static void GeneratePlugin(Options opts)
        {
            if (opts.ProjectDirectory != null)
                opts.ProjectDirectory = opts.ProjectDirectory.Replace("\"", "");
            if (opts.UprojectName != null)
                opts.UprojectName = opts.UprojectName.Replace("\"", "");
            if (opts.UnrealDirectory != null)
                opts.UnrealDirectory = opts.UnrealDirectory.Replace("\"", "");
            if (opts.PluginName != null)
                opts.PluginName = opts.PluginName.Replace("\"", "");

            double seconds = DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1)).TotalSeconds;
            string packageName = "C" + seconds.ToString().Replace(".", "");
            Package p = new Package();
            p.FriendlyName = packageName;
            opts.PluginName = packageName;
            string packageUpluginFileText = JsonConvert.SerializeObject(p, Formatting.Indented);

            string pluginDirectory = opts.ProjectDirectory + "/Plugins/" + p.FriendlyName + "/";
            Directory.CreateDirectory(pluginDirectory);
            Directory.CreateDirectory(pluginDirectory + "Config/");
            Directory.CreateDirectory(pluginDirectory + "Content/");
            Directory.CreateDirectory(pluginDirectory + "Resources/");

            string upluginFile = pluginDirectory + p.FriendlyName + ".uplugin";
            using (TextWriter tw = File.CreateText(upluginFile))
            {
                tw.Write(packageUpluginFileText);
                tw.Close();
            }

            Console.Write("Generated plugin files for " + opts.PluginName + "\n");
            OnPluginGenerated(null, null, opts);
        }

        private static void OnPluginGenerated(object sender, EventArgs e, Options opts)
        {
            string buildToolPath = opts.UnrealDirectory + "\\Engine\\Binaries\\DotNET\\UnrealBuildTool.exe";

            Process unrealBuildProcess = new Process();
            ProcessStartInfo unrealBuildProcessStartInfo = new ProcessStartInfo();
            unrealBuildProcessStartInfo.CreateNoWindow = true;
            unrealBuildProcessStartInfo.UseShellExecute = false;
            unrealBuildProcessStartInfo.FileName = buildToolPath;
            unrealBuildProcessStartInfo.WindowStyle = ProcessWindowStyle.Hidden;
            unrealBuildProcessStartInfo.RedirectStandardOutput = true;
            unrealBuildProcessStartInfo.Arguments = "-projectfiles -project=\"" + opts.GetUprojectPath() + "\"";
            unrealBuildProcess.StartInfo = unrealBuildProcessStartInfo;
            //unrealBuildProcess.Exited += (sender, e) => OnProjectFilesGenerated(sender, e, opts);

            Console.WriteLine("Starting " + unrealBuildProcessStartInfo.FileName + " " + unrealBuildProcessStartInfo.Arguments);
            unrealBuildProcess.Start();

            do
            {
                Thread.Sleep(100);
                Console.Out.Write(unrealBuildProcess.StandardOutput.ReadToEnd());
            }
            while (!unrealBuildProcess.HasExited);
            Console.Out.Write(unrealBuildProcess.StandardOutput.ReadToEnd());

            OnProjectFilesGenerated(null, null, opts);
        }

        private static void OnProjectFilesGenerated(object sender, EventArgs e, Options opts)
        {
            Process characterImportProcess = new Process();

            ProcessStartInfo characterImportProcessStartInfo = new ProcessStartInfo();
            characterImportProcessStartInfo.CreateNoWindow = true;
            characterImportProcessStartInfo.UseShellExecute = false;
            characterImportProcessStartInfo.FileName = opts.UnrealDirectory + "/Engine/Binaries/Win64/UE4Editor-Cmd.exe";
            characterImportProcessStartInfo.WindowStyle = ProcessWindowStyle.Hidden;
            characterImportProcessStartInfo.RedirectStandardOutput = true;
            characterImportProcessStartInfo.Arguments = "\"" + opts.GetUprojectPath() + "\"" + " -run=ImportAssets -importsettings=\"\"" + " -nosourcecontrol";
            characterImportProcess.StartInfo = characterImportProcessStartInfo;
            //unrealBuildProcess.Exited += (sender, e) => OnProjectFilesGenerated(sender, e, opts);

            Console.WriteLine("Starting " + characterImportProcessStartInfo.FileName + " " + characterImportProcessStartInfo.Arguments);
            characterImportProcess.Start();

            do
            {
                Thread.Sleep(100);
                Console.Out.Write(characterImportProcess.StandardOutput.ReadToEnd());
            }
            while (!characterImportProcess.HasExited);
            Console.Out.Write(characterImportProcess.StandardOutput.ReadToEnd());

            OnCharacterFilesImported(null, null, opts);
        }

        private static void OnCharacterFilesImported(object sender, EventArgs e, Options opts)
        {
            Process dlcBuildProcess = new Process();

            ProcessStartInfo dlcBuildProcessStartInfo = new ProcessStartInfo();
            dlcBuildProcessStartInfo.CreateNoWindow = true;
            dlcBuildProcessStartInfo.UseShellExecute = false;
            dlcBuildProcessStartInfo.FileName = opts.UnrealDirectory + "\\Engine\\Binaries\\DotNET\\AutomationTool.exe";
            dlcBuildProcessStartInfo.WindowStyle = ProcessWindowStyle.Hidden;
            dlcBuildProcessStartInfo.RedirectStandardOutput = true;
            dlcBuildProcessStartInfo.Arguments =
                "-ScriptsForProject=\"" + opts.GetUprojectPath() + "\" " +
                "BuildCookRun " +
                "-project=\"" + opts.GetUprojectPath() + "\" " +
                "-dlcname=" + opts.PluginName +
                " -noP4 -clientconfig=Development -serverconfig=Development -nocompile -nocompileeditor -installed -ue4exe=UE4Editor-Cmd.exe -utf8output " +
                "-platform=Win64 -targetplatform=Win64 -build -cook -unversionedcookedcontent -pak -DLCIncludeEngineContent -basedonreleaseversion=1.0 -compressed -stage -package";
            dlcBuildProcess.StartInfo = dlcBuildProcessStartInfo;

            //unrealBuildProcess.Exited += (sender, e) => OnProjectFilesGenerated(sender, e, opts);

            Console.WriteLine("Starting " + dlcBuildProcessStartInfo.FileName + " " + dlcBuildProcessStartInfo.Arguments);

            dlcBuildProcess.Start();

            do
            {
                Thread.Sleep(100);
                Console.Out.Write(dlcBuildProcess.StandardOutput.ReadToEnd());
            }
            while (!dlcBuildProcess.HasExited);
            Console.Out.Write(dlcBuildProcess.StandardOutput.ReadToEnd());

            Console.WriteLine("Press any key to continue...");
            Console.ReadKey();
        }

        private static void HandleParseError(IEnumerable<Error> errs)
        {

        }

        static void Main(string[] args)
        {
            CommandLine.Parser.Default.ParseArguments<Options>(args)
              .WithParsed<Options>(opts => GeneratePlugin(opts))
              .WithNotParsed<Options>((errs) => HandleParseError(errs));
        }
    }
}